(define x (list 1 2 3)) 
(define val1 (cons 1 2))
(define val2 (cons 1 '()))
(define val3 7)
(pair? x)
(pair? val1)
(pair? val2)
(pair? val3)
(list? x)
(list? val1)
(list? val2)
(list? val3)
(define val6 1)
(null? val6)
(define val5 '())
(null? val5)
(null? val1)
(null? val2)
(null? val3)
(list? (cons 3 '()))
(list? (cons 3 4))  ; 这个是#f
(pair? (cons 3 '()))
(pair? (cons 3 4))