(load "./ch2/2_58/=number.scm")

(define (make-product m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0))
          0)
        ((=number? m1 1)
          m2)
        ((=number? m2 1)
          m1)
        ((and (number? m1) (number? m2))
          (* m1 m2))
        (else
          (list m1 '* m2))))

(define (product? x) 
  (and (pair? x) 
       (eq? (cadr x) '*)))
(define (multiplier p) 
  (car p))
(define (multiplicand p) 
  (caddr p))