(define (make-account balance secret)
  (define (withdraw amount) 
    (if (>= balance amount) 
        (begin (set! balance (- balance amount)) 
               balance) 
               "Insufficient funds")) 
  (define (deposit amount) 
    ; 这里可带begin, 也可不带?
    (begin (set! balance (+ balance amount)) 
           balance))
  (define (dispatch password mt) 
    (if (eq? password secret)
        (cond ((eq? mt 'withdraw) withdraw)
              ((eq? mt 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT" m))) 
        (error "密码错误 " password)))
  dispatch)
(define acc (make-account 100 'pass123))
((acc 'pass123 'withdraw) 50)
((acc 'pass123 'withdraw) 60)
((acc 'pass123 'deposit) 40)
((acc 'pass123 'withdraw) 60)

((acc 'sdf 'withdraw) 10)