(define (or-gate a1 a2 output)
  (define (or-action-procedure) 
    (let ((new-value (logical-or (get-signal a1) (get-signal a2))))
      (after-delay or-gate-delay
                   (lambda () (set-signal! output new-value))))) 

  (add-action! a1 or-action-procedure) 
  (add-action! a2 or-action-procedure) 
  'ok)
(define (logical-or wire1 wire2)
  (cond ((and (= wire1 0)
              (= wire2 0)) 0)
        ((or (= wire1 1)
             (= wire2 1)) 1)
        (else (error "Invalid signal" wire1 wire2))))