(define (average x y) (/ (+ x y) 2))
(define (sqrt-improve guess x) (average guess (/ x guess)))
(define (sqrt-stream x)
  (define guesses (cons-stream 1.0 (stream-map (lambda (guess) 
                                                        (sqrt-improve guess x)) 
                                               guesses))) 
  guesses)
(stream-head (sqrt-stream 2) 10)