(load "./ch1/1_31/pi.scm")

(numerator-m 1)
(numerator-m 2)
(numerator-m 3)
(numerator-m 4)
(numerator-m 5)
(denominator-m 1)
(denominator-m 2)
(denominator-m 3)
(denominator-m 4)
(denominator-m 5)
(term 1)
(term 2)
(term 3)
(term 4)
(term 5)